version: "3.8"

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network
  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network
  file-management:
    build: ./file-management
    container_name: file_management_service
    ports:
      - "8004:8000"
    networks:
      - app-network

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api_gateway
    ports:
      - "8000:8000"
    volumes:
      - ./api-gateway:/var/www/html
    command: php artisan serve --host=0.0.0.0 --port=8000
    networks:
      - app-network
    depends_on:
      - rabbitmq
  security:
    build: ./security
    container_name: security_service
    ports:
      - "8001:8000"
    networks:
      - app-network

  notification:
    build: ./notification
    container_name: notification_service
    ports:
      - "8002:8000"
    networks:
      - app-network
    depends_on:
      - rabbitmq
      - redis
  license:
    build: ./license
    container_name: license_service
    ports:
      - "8003:8000"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
